#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_historical_index:
    path: /historical
    controller: App\Controller\HistoricalController::indexAction
app_historical_email:
    path: /historical/email
    controller: App\Controller\HistoricalController::emailAction
